### ISSUE TITLE
react4xp.properties and SSR functionality

### ISSUE THREAD

**Issue by espen42** [enonic/demo-react4xp#20]
- [x] Somewhere, react4xp.properties should be mentioned. A new chapter?
- [x] There, talk about the role of gradle and NPM-react4xp
- [x] And about adding webpack functionality
- [x] And about SSR functionality and config:
    - [x] ssrSettings
    - [x] ssrLazyload and warmup time 
    - [x] ssrMaxthreads
- [x] buildEnv and effects on...
    - [x] code
    - [x] sourcemaps
    - [x] performance
- [x] #16 
- [x] Describe case and solutions for [#160](https://github.com/enonic/lib-react4xp/issues/160) and [#161](https://github.com/enonic/lib-react4xp/issues/161) in doc-react4xp

**Comment by espen42** [comment]
Plan: add to API chapter instead:

- [x] Present SSR engine and nashorn
- [x] Startup times
- [x] Mention defaults: multitasking, no-cache
- [x] Present config: react4xp.properties
    - [x] buildEnv, and effect on lazyload and compilation
    - [x] ssrLazyload
    - [x] ssrMaxThreads
    - [x] ssrSettings
    - [x] react4xp.properties needs gradle setup
    - [x] Compilation control 
        - [x] Idea: webpack set up to compile sources to isomorphic code
        - [x] Chunkdirs, entrydirs
        - [x] Webpack override
        - [x] Nashornpolyfills and override
