### ISSUE TITLE
Simplify the react4xp docs

### ISSUE THREAD

**Issue by sigdestad** [enonic/demo-react4xp#77]
The current examples and chapters need general refactoring and simplification.
```[tasklist]
### Tasks
- [ ] https://github.com/enonic/doc-react4xp/issues/65
- [ ] https://github.com/enonic/doc-react4xp/issues/64
- [ ] https://github.com/enonic/doc-react4xp/issues/63
- [ ] https://github.com/enonic/doc-react4xp/issues/62
- [ ] https://github.com/enonic/doc-react4xp/issues/51
- [ ] https://github.com/enonic/doc-react4xp/issues/50
- [ ] https://github.com/enonic/doc-react4xp/issues/49
- [ ] https://github.com/enonic/doc-react4xp/issues/48
```
